app:
  auth:
  
    token:
      expiration: 86400000
      prefix: Bearer
      secret: asdSD434jri33klj4KLJH2dfj4h3JH
      claims:
        permissions:
          name: Permissions
        group:
          name: Group
          
    apikey:
      prefix: ApiKey
      
    shared:
      prefix: Shared
      value: 234s8d9fs2hl3hsdf8
      group: app
