app:
  auth:
  
    token:
      expiration: 86400000
      prefix: Bearer
      secret: asdSD434jri33klj4KLJH2dfj4h3JH
      claims:
        permissions:
          name: Permissions
          
    apiKey:
      prefix: ApiKey
      secret: skeh3uahen14U4R3
      
    shared:
      prefix: Shared
      value: 234s8d9fs2hl3hsdf8
      group: app

    permissions:
      groups:        
      - user:
        - 'iot.fleet.permission.account.update'
        - 'iot.fleet.permission.account.delete'
        - 'iot.fleet.permission.account.exists'
        - 'iot.fleet.permission.account.show'
        - 'iot.fleet.permission.jwt.create'
        - 'iot.fleet.permission.jwt.delete'
        
        - 'iot.fleet.permission.apikey.create'
        - 'iot.fleet.permission.apikey.show'
        
        - 'iot.fleet.permission.device.*'
        - 'iot.fleet.permission.pilot.*'
        - 'iot.fleet.permission.missionPrototype.*'
        - 'iot.fleet.permission.mission.create'
        
      - device:
        - 'iot.fleet.permission.device.show'
        - 'iot.fleet.permission.device.update'
        - 'iot.fleet.permission.device.connect'
      
      - pilot:
        - 'iot.fleet.permission.device.show'
        - 'iot.fleet.permission.device.update'

        - 'iot.fleet.permission.pilot.show'
        - 'iot.fleet.permission.pilot.update'
        - 'iot.fleet.permission.pilot.connect'
      
      - edge:
        - 'iot.fleet.permission.account.show'
        - 'iot.fleet.permission.pilot.update'
        - 'iot.fleet.permission.device.update'
        - 'iot.fleet.permission.server.update'
        
      - worker:
        - 'iot.fleet.permission.server.update'
        - 'iot.fleet.permission.pilot.update'
        - 'iot.fleet.permission.mission.update'
      
      - admin:
        - 'iot.fleet.permission.admin.actuator'
        - 'iot.fleet.permission.apikey.*'
        
        - 'iot.fleet.permission.server.create'
        - 'iot.fleet.permission.server.show'
