app:
  auth:
  
    token:
      expiration: 86400000
      prefix: Bearer
      secret: asdSD434jri33klj4KLJH2dfj4h3JH
      claims:
        permissions:
          name: Permissions
          
    apiKey:
      prefix: ApiKey
      secret: skeh3uahen14U4R3
      
    shared:
      prefix: Shared
      value: 234s8d9fs2hl3hsdf8
      group: app

    permissions:
      groups:        
      - user:
        - 'iot.fleet.permission.account.update'
        - 'iot.fleet.permission.account.delete'
        - 'iot.fleet.permission.jwt.create'
        - 'iot.fleet.permission.jwt.delete'
        
        - 'iot.fleet.permission.apikey.create'
        - 'iot.fleet.permission.apikey.show'
        
        - 'iot.fleet.permission.device.*'
        - 'iot.fleet.permission.pilot.*'
        - 'iot.fleet.permission.operation.show'
        - 'iot.fleet.permission.operation.list'
        
      - device:
        - 'iot.fleet.permission.device.update'
      
      - pilot:
        - 'iot.fleet.permission.device.update'
        - 'iot.fleet.permission.pilot.update'
      
      - edge:
        - 'iot.fleet.permission.operation.create'
        - 'iot.fleet.permission.operation.update'
        - 'iot.fleet.permission.operation.delete'
        
        - 'iot.fleet.permission.pilot.update'
        - 'iot.fleet.permission.pilot.owner'
        
        - 'iot.fleet.permission.device.update'
        - 'iot.fleet.permission.device.owner'
        
        - 'iot.fleet.permission.edge.create'
        
      - app:
        - 'iot.fleet.permission.admin.actuator'
      
      - admin:
        - 'iot.fleet.permission.admin.*'
        - 'iot.fleet.permission.apikey.*'
